### PR TITLE
Add support for EL7

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Please don't merge yet as I'm still testing.

**Comment by ghoneycutt** [comment]
Hi @ngrossmann 

Could you please merge this?

**Comment by ngrossmann** [comment]
Hi @ghoneycutt,
merged and created release v0.3.0.

**Comment by ghoneycutt** [comment]
Thanks @ngrossmann

**Pull request merged**
